<?php

use App\Support\CaptchaTokenTransformer;

/**
 * Parity tests: PHP output must be byte-identical to the live IVAC bundle.
 *
 * Reference values generated by executing the live bundle's encrypt modules in Node — June 11 2026.
 *   LOGIN  (version 6): polynomial-in-k mod 67 shift schedule (additive), skip=7, encLen=23
 *   RESERVE (version 5): three-LFSR multiplexer shift schedule (additive), skip=4, encLen=22
 *
 * NOTE: As of September 2026, IVAC rotated to version 2 for both types (skip=4, encLen=26).
 * These tests verify the PHP algorithm implementations remain correct for their original parameters.
 * Current live parameters are tested via CaptchaAlgorithmGroundTruthTest and the Node sidecar.
 */

const TEST_LOGIN_SECRET = '671hnk6vg7e5hnv$4fy+7-_ch_io0)q$_xz=k++r-^&i32dfst';
const TEST_LOGIN_SKIP = 7;
const TEST_LOGIN_ENC_LEN = 23;

const TEST_RESERVE_SECRET = '@541m3tp&t63noy&3ngwa%fgfivy3n1_7d)zvj$h-au+bah50f';
const TEST_RESERVE_SKIP = 4;
const TEST_RESERVE_ENC_LEN = 22;

describe('CaptchaTokenTransformer::transformLogin', function () {

    it('produces output matching the live bundle', function () {
        $token = '0.Abc123-_xYzDEFghijklmNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        $expected = '0.Abc12Q10cZ_VGO3pTNBfbcVnQVcVUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';

        expect(CaptchaTokenTransformer::transformLogin($token, TEST_LOGIN_SECRET, TEST_LOGIN_SKIP, TEST_LOGIN_ENC_LEN))->toBe($expected);
    });

    it('leaves the first 7 chars and everything after position 30 unchanged', function () {
        $token = '0.Abc123-_xYzDEFghijklmNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        $result = CaptchaTokenTransformer::transformLogin($token, TEST_LOGIN_SECRET, TEST_LOGIN_SKIP, TEST_LOGIN_ENC_LEN);

        expect(substr($result, 0, 7))->toBe(substr($token, 0, 7));
        expect(substr($result, 30))->toBe(substr($token, 30));
    });

    it('returns empty string unchanged', function () {
        expect(CaptchaTokenTransformer::transformLogin('', TEST_LOGIN_SECRET, TEST_LOGIN_SKIP, TEST_LOGIN_ENC_LEN))->toBe('');
    });

    it('returns tokens shorter than skip (7) unchanged', function () {
        expect(CaptchaTokenTransformer::transformLogin('abc', TEST_LOGIN_SECRET, TEST_LOGIN_SKIP, TEST_LOGIN_ENC_LEN))->toBe('abc');
    });

    it('is deterministic', function () {
        $token = '0.Abc123-_xYzDEFghijklmNOPQRSTUVWXYZ';

        expect(CaptchaTokenTransformer::transformLogin($token, TEST_LOGIN_SECRET, TEST_LOGIN_SKIP, TEST_LOGIN_ENC_LEN))
            ->toBe(CaptchaTokenTransformer::transformLogin($token, TEST_LOGIN_SECRET, TEST_LOGIN_SKIP, TEST_LOGIN_ENC_LEN));
    });
});

describe('CaptchaTokenTransformer::transformReserve', function () {

    it('produces output matching the live bundle', function () {
        $token = '0.Abc123-_xYzDEFghijklmNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        $expected = '0.Ab9oqkReVQtWZXiK5jBAbC3vQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';

        expect(CaptchaTokenTransformer::transformReserve($token, TEST_RESERVE_SECRET, TEST_RESERVE_SKIP, TEST_RESERVE_ENC_LEN))->toBe($expected);
    });

    it('leaves the first 4 chars and everything after position 26 unchanged', function () {
        $token = '0.Abc123-_xYzDEFghijklmNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        $result = CaptchaTokenTransformer::transformReserve($token, TEST_RESERVE_SECRET, TEST_RESERVE_SKIP, TEST_RESERVE_ENC_LEN);

        expect(substr($result, 0, 4))->toBe(substr($token, 0, 4));
        expect(substr($result, 26))->toBe(substr($token, 26));
    });

    it('returns empty string unchanged', function () {
        expect(CaptchaTokenTransformer::transformReserve('', TEST_RESERVE_SECRET, TEST_RESERVE_SKIP, TEST_RESERVE_ENC_LEN))->toBe('');
    });

    it('encrypts a single char beyond the skip prefix', function () {
        // 'abcde' → prefix='abcd' (4 chars), encrypt 'e' additively → 'b'
        expect(CaptchaTokenTransformer::transformReserve('abcde', TEST_RESERVE_SECRET, TEST_RESERVE_SKIP, TEST_RESERVE_ENC_LEN))->toBe('abcdb');
    });

    it('is deterministic', function () {
        $token = '0.Abc123-_xYzDEFghijklmNOPQRSTUVWXYZ';

        expect(CaptchaTokenTransformer::transformReserve($token, TEST_RESERVE_SECRET, TEST_RESERVE_SKIP, TEST_RESERVE_ENC_LEN))
            ->toBe(CaptchaTokenTransformer::transformReserve($token, TEST_RESERVE_SECRET, TEST_RESERVE_SKIP, TEST_RESERVE_ENC_LEN));
    });
});
