<?php

namespace App\Support;

use DateTimeImmutable;

/**
 * Reads the applicant's identity fields out of an Indian visa application form PDF.
 *
 * The form is generated by the Indian visa portal with a fixed two-column layout, so every value
 * sits on the same baseline as its label at a known x. Locating values geometrically (rather than
 * by reading order) is what makes this survive the overlays the portal's own
 * app/Scripts/edit_passport_pdf.py writes, which append the replacement text far away from the
 * original reading position.
 *
 * Text is recovered from the page content streams directly — no PDF library — so this stays free
 * of dependencies. Anything it cannot find is returned as null and simply stays empty on the form.
 */
class VisaFormPdfParser
{
    /**
     * Label text paired with the x origin of its value column, taken from the generated layout.
     *
     * @var array<string, array{string, float}>
     */
    private const FIELDS = [
        'surname' => ['Surname (As in Passport)', 177.74],
        'given_name' => ['Given Name (As in Passport)', 177.74],
        'dob' => ['Date of Birth', 177.74],
        'nid' => ['Citizenship /National ID No', 177.74],
        'passport' => ['Passport No.', 132.91],
        'email' => ['Email address', 373.93],
    ];

    /**
     * Phone labels in preference order. "Phone No" is the number the agents actually register with;
     * "Mobile /Cell No" is the applicant's own line and only serves as a fallback.
     *
     * @var array<int, array{string, float}>
     */
    private const PHONE_FIELDS = [
        ['Phone No', 373.93],
        ['Mobile /Cell No', 373.93],
    ];

    private const X_TOLERANCE = 14.0;

    private const Y_TOLERANCE = 4.0;

    /**
     * @return array{surname: ?string, given_name: ?string, dob: ?string, nid: ?string, passport: ?string, phone: ?string, email: ?string}
     */
    public static function extract(string $pdf): array
    {
        $items = [];
        foreach (self::contentStreams($pdf) as $index => $content) {
            foreach (self::textItems($content) as $item) {
                $item['stream'] = $index;
                $items[] = $item;
            }
        }

        $items = self::groupStreamsByPage($items);

        $fields = [];
        foreach (self::FIELDS as $key => [$label, $valueX]) {
            $fields[$key] = self::valueFor($items, $label, $valueX);
        }

        return [
            'surname' => self::cleanName($fields['surname']),
            'given_name' => self::cleanName($fields['given_name']),
            'dob' => self::normalizeDate($fields['dob']),
            'nid' => self::digitsOrNull($fields['nid']),
            'passport' => self::cleanCode($fields['passport']),
            'phone' => self::extractPhone($items),
            'email' => self::normalizeEmail($fields['email']),
        ];
    }

    /**
     * Every string painted on the document, concatenated in the order it was drawn.
     *
     * Reading order carries no meaning here — this exists for values whose position cannot be
     * trusted, such as the "Web Registration Date" rotated down the left margin, whose glyphs a
     * positional read interleaves with the column printed beside it.
     */
    public static function rawText(string $pdf): string
    {
        $text = '';
        foreach (self::contentStreams($pdf) as $content) {
            foreach (self::textItems($content) as $item) {
                $text .= $item['text'];
            }
        }

        return $text;
    }

    /**
     * The "Application Id" IVAC prints beneath the photo barcode — the web file number, e.g.
     * BGDDVBA47626.
     *
     * Read out of painting order rather than page position: the value is painted immediately after
     * its label but sits in a header band whose neighbouring runs a positional read mixes in, and
     * the very next string on the page ("Paste your unsigned...") concatenates straight onto it, so
     * the length is pinned at the 12 characters IVAC issues instead of matched greedily.
     */
    public static function applicationId(string $pdf): ?string
    {
        if (preg_match('/Application\s*Id\s*:?\s*(BGD[A-Z0-9]{9})/i', self::rawText($pdf), $matches) !== 1) {
            return null;
        }

        return strtoupper($matches[1]);
    }

    /**
     * Values are only ever read off the page that carries their label, which keeps one page's
     * labels from claiming another's values. Edited PDFs break that per-stream assumption: PyMuPDF
     * appends each replacement as its own content stream, so a stream holding no labels at all is
     * folded into the last stream that did — the page it was painted onto.
     *
     * @param  array<int, array{x: float, y: float, text: string, stream: int}>  $items
     * @return array<int, array{x: float, y: float, text: string, stream: int}>
     */
    private static function groupStreamsByPage(array $items): array
    {
        $labels = array_merge(
            array_column(self::FIELDS, 0),
            array_column(self::PHONE_FIELDS, 0),
        );

        $group = [];
        $current = 0;
        foreach ($items as $item) {
            if (! array_key_exists($item['stream'], $group)) {
                $group[$item['stream']] = $current;
            }
            if (in_array(trim($item['text']), $labels, true)) {
                $current = $group[$item['stream']] = $item['stream'];
            }
        }

        foreach ($items as $index => $item) {
            $items[$index]['stream'] = $group[$item['stream']];
        }

        return $items;
    }

    /**
     * Inflate every page/form content stream. Images and the cross-reference/object streams are
     * skipped: they never carry text operators and their predictors would not inflate cleanly.
     *
     * @return array<int, string>
     */
    private static function contentStreams(string $pdf): array
    {
        $streams = [];
        $offset = 0;

        while (($position = strpos($pdf, 'stream', $offset)) !== false) {
            $offset = $position + 6;
            $dictStart = strrpos(substr($pdf, 0, $position), '<<');
            if ($dictStart === false) {
                continue;
            }

            $dict = substr($pdf, $dictStart, $position - $dictStart);
            if (! str_contains($dict, 'FlateDecode')
                || str_contains($dict, '/Image')
                || str_contains($dict, '/ObjStm')
                || str_contains($dict, '/XRef')
                || str_contains($dict, '/DecodeParms')) {
                continue;
            }

            $start = $offset;
            if (($pdf[$start] ?? '') === "\r") {
                $start++;
            }
            if (($pdf[$start] ?? '') === "\n") {
                $start++;
            }

            $end = strpos($pdf, 'endstream', $start);
            if ($end === false) {
                break;
            }

            $inflated = @gzuncompress(substr($pdf, $start, $end - $start));
            if ($inflated !== false) {
                $streams[] = $inflated;
            }
        }

        return $streams;
    }

    /**
     * Walk the text operators of one content stream, tracking the text matrix so each drawn string
     * carries the position it was painted at.
     *
     * @return array<int, array{x: float, y: float, text: string}>
     */
    private static function textItems(string $content): array
    {
        $pattern = '/(?P<hex><[0-9A-Fa-f\s]*>)'
            .'|(?P<num>-?[\d.]+)'
            .'|(?P<op>Tm|TD|Td|T\*|TL|Tj|TJ|BT)'
            .'|(?P<str>\((?:\\\\.|[^\\\\()])*\))'
            .'|(?P<arr>\[(?:\\\\.|\((?:\\\\.|[^\\\\()])*\)|[^\\\\\[\]])*\])/s';

        preg_match_all($pattern, $content, $matches, PREG_SET_ORDER);

        $items = [];
        $operands = [];
        $lineX = 0.0;
        $lineY = 0.0;
        $x = 0.0;
        $y = 0.0;
        $leading = 0.0;

        foreach ($matches as $match) {
            if (($match['num'] ?? '') !== '') {
                $operands[] = (float) $match['num'];

                continue;
            }
            if (($match['hex'] ?? '') !== '' || ($match['str'] ?? '') !== '' || ($match['arr'] ?? '') !== '') {
                $operands[] = $match[0];

                continue;
            }

            switch ($match['op']) {
                case 'BT':
                    $lineX = $lineY = $x = $y = 0.0;
                    break;
                case 'Tm':
                    if (count($operands) >= 6) {
                        $matrix = array_slice($operands, -6);
                        $lineX = $x = (float) $matrix[4];
                        $lineY = $y = (float) $matrix[5];
                    }
                    break;
                case 'TD':
                case 'Td':
                    if (count($operands) >= 2) {
                        $shift = array_slice($operands, -2);
                        if ($match['op'] === 'TD') {
                            $leading = -(float) $shift[1];
                        }
                        $lineX += (float) $shift[0];
                        $lineY += (float) $shift[1];
                        $x = $lineX;
                        $y = $lineY;
                    }
                    break;
                case 'TL':
                    if ($operands !== []) {
                        $leading = (float) end($operands);
                    }
                    break;
                case 'T*':
                    $lineY -= $leading;
                    $x = $lineX;
                    $y = $lineY;
                    break;
                case 'Tj':
                case 'TJ':
                    $text = self::decodeStrings((string) end($operands));
                    if (trim($text) !== '') {
                        $items[] = ['x' => $x, 'y' => $y, 'text' => $text];
                    }
                    break;
            }

            $operands = [];
        }

        return $items;
    }

    /**
     * Concatenate the strings inside a Tj operand or a TJ array, dropping the kerning numbers that
     * sit between them. Both notations appear in practice: the form itself uses literal strings,
     * while the text PyMuPDF overlays onto an edited PDF is written as hex.
     */
    private static function decodeStrings(string $operand): string
    {
        preg_match_all('/\((?:\\\\.|[^\\\\()])*\)|<[0-9A-Fa-f\s]*>/s', $operand, $matches);

        $text = '';
        foreach ($matches[0] as $token) {
            $text .= $token[0] === '('
                ? stripcslashes(substr($token, 1, -1))
                : self::decodeHexString($token);
        }

        return $text;
    }

    /**
     * A hex string only counts when it decodes to printable ASCII — under a subset font the same
     * notation carries glyph ids, which would otherwise turn into noise in a field.
     */
    private static function decodeHexString(string $token): string
    {
        $hex = preg_replace('/[^0-9A-Fa-f]/', '', substr($token, 1, -1)) ?? '';
        if (strlen($hex) % 2 === 1) {
            $hex .= '0';
        }

        $decoded = hex2bin($hex);

        return ($decoded === false || preg_match('/^[\x20-\x7e]*$/', $decoded) !== 1) ? '' : $decoded;
    }

    /**
     * @param  array<int, array{x: float, y: float, text: string, stream: int}>  $items
     */
    private static function valueFor(array $items, string $label, float $valueX): ?string
    {
        $value = null;

        foreach ($items as $candidate) {
            $labelItem = self::matchingLabel($items, $candidate, $label, $valueX);
            if ($labelItem === null) {
                continue;
            }

            // Last painted wins: an edited PDF appends the replacement over the redacted original.
            $value = trim($candidate['text']);
        }

        return ($value === null || $value === '') ? null : $value;
    }

    /**
     * Return the label item this candidate is the value of, or null when it is not one.
     *
     * @param  array<int, array{x: float, y: float, text: string, stream: int}>  $items
     * @param  array{x: float, y: float, text: string, stream: int}  $candidate
     * @return array{x: float, y: float, text: string, stream: int}|null
     */
    private static function matchingLabel(array $items, array $candidate, string $label, float $valueX): ?array
    {
        if (abs($candidate['x'] - $valueX) > self::X_TOLERANCE) {
            return null;
        }

        foreach ($items as $item) {
            if ($item['stream'] !== $candidate['stream']
                || trim($item['text']) !== $label
                || abs($item['y'] - $candidate['y']) > self::Y_TOLERANCE
                || $item['x'] >= $candidate['x']) {
                continue;
            }

            return $item;
        }

        return null;
    }

    /**
     * The form carries several "Phone No" labels (the applicant's, the host hotel's, the
     * references'), so a value only counts when it also looks like a Bangladeshi mobile number.
     *
     * @param  array<int, array{x: float, y: float, text: string, stream: int}>  $items
     */
    private static function extractPhone(array $items): ?string
    {
        foreach (self::PHONE_FIELDS as [$label, $valueX]) {
            $phone = self::normalizePhone(self::valueFor($items, $label, $valueX));
            if ($phone !== null) {
                return $phone;
            }
        }

        return null;
    }

    /** Reduce the many written forms (88…, 8801…, +88…) to the local 01XXXXXXXXX the portal uses. */
    private static function normalizePhone(?string $raw): ?string
    {
        if ($raw === null) {
            return null;
        }

        $digits = preg_replace('/\D+/', '', $raw) ?? '';
        if (preg_match('/(1[3-9]\d{8})$/', $digits, $matches) !== 1) {
            return null;
        }

        return '0'.$matches[1];
    }

    /** The form prints dates as 01-OCT-2003; the signup form wants an ISO date. */
    private static function normalizeDate(?string $raw): ?string
    {
        if ($raw === null) {
            return null;
        }

        $date = DateTimeImmutable::createFromFormat('!d-M-Y', ucfirst(strtolower(trim($raw))));

        return $date === false ? null : $date->format('Y-m-d');
    }

    private static function normalizeEmail(?string $raw): ?string
    {
        if ($raw === null) {
            return null;
        }

        $email = strtolower(trim($raw));

        return filter_var($email, FILTER_VALIDATE_EMAIL) === false ? null : $email;
    }

    private static function cleanName(?string $raw): ?string
    {
        if ($raw === null) {
            return null;
        }

        $name = preg_replace('/\s+/', ' ', trim($raw)) ?? '';

        return $name === '' ? null : $name;
    }

    private static function cleanCode(?string $raw): ?string
    {
        if ($raw === null) {
            return null;
        }

        $code = strtoupper(preg_replace('/\s+/', '', $raw) ?? '');

        return $code === '' ? null : $code;
    }

    private static function digitsOrNull(?string $raw): ?string
    {
        if ($raw === null) {
            return null;
        }

        $digits = preg_replace('/\D+/', '', $raw) ?? '';

        return $digits === '' ? null : $digits;
    }
}
